-- MySQL Script generated by MySQL Workbench
-- Sun May 23 00:31:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accesoriossimple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accesoriossimple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accesoriossimple` DEFAULT CHARACTER SET utf8 ;
USE `accesoriossimple` ;

-- -----------------------------------------------------
-- Table `accesoriossimple`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `tipo_documento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documento` BIGINT NOT NULL,
  `telefono` BIGINT NOT NULL,
  `rol` ENUM('Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `user` VARCHAR(100) NULL,
  `password` VARCHAR(150) NULL,
  `foto` VARCHAR(45) NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_compras` DATETIME NOT NULL,
  `numero_factura` BIGINT NOT NULL,
  `valortotal` BIGINT NOT NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IdCompras_UNIQUE` (`id` ASC),
  INDEX `fk_Compras_Usuario_idx` (`Proveedor_Id` ASC),
  CONSTRAINT `fk_Compras_Usuario`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`Categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`marca` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Marca_Usuario1_idx` (`Proveedor_Id` ASC),
  CONSTRAINT `fk_Marca_Usuario1`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Marca_id` INT NOT NULL,
  `Talla` SET('S', 'M', 'L', 'XL', 'XXL') NULL,
  `precio` BIGINT NOT NULL,
  `estado` ENUM('Disponibilidad', 'Nodisponible') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProducto_UNIQUE` (`id` ASC),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_id` ASC),
  INDEX `fk_Producto_Marca1_idx` (`Marca_id` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `accesoriossimple`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `accesoriossimple`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`cotizacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `Cliente_Id` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `valido_dias` BIGINT NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idDetalle-venta_UNIQUE` (`id` ASC),
  INDEX `fk_Cotizacion_Usuario1_idx` (`Cliente_Id` ASC),
  CONSTRAINT `fk_Cotizacion_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_factura` TINYINT(200) NOT NULL,
  `fecha_factura` DATE NOT NULL,
  `valor_factura` BIGINT NOT NULL,
  `estado` ENUM('En Proceso', 'En Camino', 'Entregado') NOT NULL,
  `tipo_venta` ENUM('Directa', 'Accesoria', 'Telefonica', 'TiendaOnline', 'Apartado') NOT NULL,
  `Cotizacion_Id` INT NULL,
  `Cliente_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idfactura_UNIQUE` (`id` ASC),
  INDEX `fk_factura_Accesoria1_idx` (`Cotizacion_Id` ASC),
  INDEX `fk_Venta_Usuario1_idx` (`Cliente_Id` ASC),
  CONSTRAINT `fk_factura_Accesoria1`
    FOREIGN KEY (`Cotizacion_Id`)
    REFERENCES `accesoriossimple`.`cotizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`color` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock` BIGINT NOT NULL,
  `Producto_IdProducto` INT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Color_Producto1_idx` (`Producto_IdProducto` ASC),
  CONSTRAINT `fk_Color_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `accesoriossimple`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`detalle_ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `factura_Id` INT NOT NULL,
  `color_Id` INT NOT NULL,
  `cantidad` BIGINT NOT NULL,
  `precio_venta` BIGINT NOT NULL,
  `talla` CHAR(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idVentas_UNIQUE` (`id` ASC),
  INDEX `fk_Ventas_factura1_idx` (`factura_Id` ASC),
  INDEX `fk_Detalle-Ventas_Color1_idx` (`color_Id` ASC),
  CONSTRAINT `fk_Ventas_factura1`
    FOREIGN KEY (`factura_Id`)
    REFERENCES `accesoriossimple`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle-Ventas_Color1`
    FOREIGN KEY (`color_Id`)
    REFERENCES `accesoriossimple`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`fotos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `descripcion` VARCHAR(45) NULL,
  `ruta` VARCHAR(90) NOT NULL,
  `Color_idColor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Foto_Color1_idx` (`Color_idColor` ASC),
  CONSTRAINT `fk_Foto_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `accesoriossimple`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`cotizacion_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`cotizacion_productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cotizacion_id` INT NOT NULL,
  `Color_idColor` INT NOT NULL,
  `cantidad` BIGINT NOT NULL,
  `precio_venta` BIGINT NOT NULL,
  `talla` CHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cotizacion_Productos_Cotizacion1_idx` (`Cotizacion_id` ASC),
  INDEX `fk_Cotizacion_Productos_Color1_idx` (`Color_idColor` ASC),
  CONSTRAINT `fk_Cotizacion_Productos_Cotizacion1`
    FOREIGN KEY (`Cotizacion_id`)
    REFERENCES `accesoriossimple`.`cotizacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotizacion_Productos_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `accesoriossimple`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`detalle_compra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `compra_Id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `cantidad` BIGINT NOT NULL,
  `precio` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetalleCompra_Compras1_idx` (`compra_Id` ASC),
  INDEX `fk_DetalleCompra_Color1_idx` (`color_id` ASC),
  CONSTRAINT `fk_DetalleCompra_Compras1`
    FOREIGN KEY (`compra_Id`)
    REFERENCES `accesoriossimple`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_Color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `accesoriossimple`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
