-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 23:09:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PROYECTO ACCESORIO SIMPLE INVENTARIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PROYECTO ACCESORIO SIMPLE INVENTARIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO` DEFAULT CHARACTER SET utf8 ;
USE `PROYECTO ACCESORIO SIMPLE INVENTARIO` ;

-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Nit` TINYINT NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `idEmpresa_UNIQUE` (`idEmpresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Cedula` BIGINT NOT NULL,
  `telefono` BIGINT NOT NULL,
  `Rol` ENUM('cliente', 'proveedor', 'Administrativo') NOT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`IdUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Compras` (
  `IdCompras` INT NOT NULL AUTO_INCREMENT,
  `FechaDeCompras` DATE NOT NULL,
  `NumeroDeFactura` TINYINT(200) NOT NULL,
  `ValorTotal` TINYINT(200) NOT NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`IdCompras`),
  UNIQUE INDEX `IdCompras_UNIQUE` (`IdCompras` ASC) VISIBLE,
  INDEX `fk_Compras_Usuario_idx` (`Proveedor_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Usuario`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Marca` (
  `idMarca` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Usuario1_idx` (`Proveedor_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Usuario1`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Marca_id` INT NOT NULL,
  `Talla` SET('S', 'M', 'L', 'XL', 'XXL') NULL,
  `IVA` VARCHAR(45) NOT NULL,
  `Precio_Base` DOUBLE NOT NULL,
  `Estado` ENUM('Disponibilidad', 'Nodisponible') NOT NULL,
  PRIMARY KEY (`IdProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`IdProducto` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_id` ASC) VISIBLE,
  INDEX `fk_Producto_Marca1_idx` (`Marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion` (
  `idCotizacion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Cliente_Id` INT NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `ValidoDias` INT NOT NULL,
  `ValorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idCotizacion`),
  UNIQUE INDEX `idDetalle-venta_UNIQUE` (`idCotizacion` ASC) VISIBLE,
  INDEX `fk_Cotizacion_Usuario1_idx` (`Cliente_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Cotizacion_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Venta` (
  `IdVenta` INT NOT NULL AUTO_INCREMENT,
  `NumerodeFactura` TINYINT(200) NOT NULL,
  `FechadeFactura` DATE NOT NULL,
  `ValorDeFactura` SMALLINT NOT NULL,
  `Estado` ENUM('En Proceso', 'En Camino', 'Entregado') NOT NULL,
  `TipoDeVenta` ENUM('Directa', 'Accesoria', 'Telefonica', 'TiendaOnline', 'Apartado') NOT NULL,
  `Cotizacion_Id` INT NULL,
  `Cliente_Id` INT NOT NULL,
  PRIMARY KEY (`IdVenta`),
  UNIQUE INDEX `idfactura_UNIQUE` (`IdVenta` ASC) VISIBLE,
  INDEX `fk_factura_Accesoria1_idx` (`Cotizacion_Id` ASC) VISIBLE,
  INDEX `fk_Venta_Usuario1_idx` (`Cliente_Id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_Accesoria1`
    FOREIGN KEY (`Cotizacion_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion` (`idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Cliente_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color` (
  `idColor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Stock` INT NOT NULL,
  `Producto_IdProducto` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idColor`),
  INDEX `fk_Color_Producto1_idx` (`Producto_IdProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Color_Producto1`
    FOREIGN KEY (`Producto_IdProducto`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Detalle_Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Factura_Id` INT NOT NULL,
  `Color_Id` INT NOT NULL,
  `Cantidad` TINYINT(100) NOT NULL,
  `PrecioVenta` SMALLINT NOT NULL,
  `Talla` CHAR(3) NULL,
  PRIMARY KEY (`idVentas`),
  UNIQUE INDEX `idVentas_UNIQUE` (`idVentas` ASC) VISIBLE,
  INDEX `fk_Ventas_factura1_idx` (`Factura_Id` ASC) VISIBLE,
  INDEX `fk_Detalle-Ventas_Color1_idx` (`Color_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_factura1`
    FOREIGN KEY (`Factura_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Venta` (`IdVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle-Ventas_Color1`
    FOREIGN KEY (`Color_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Foto` (
  `idFoto` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `ruta` VARCHAR(90) NOT NULL,
  `Color_idColor` INT NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `fk_Foto_Color1_idx` (`Color_idColor` ASC) VISIBLE,
  CONSTRAINT `fk_Foto_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion_Productos` (
  `idCotizacion_Producto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cotizacion_id` INT NOT NULL,
  `Color_idColor` INT NOT NULL,
  `Cantidad` MEDIUMINT NOT NULL,
  `Precio_Venta` VARCHAR(45) NOT NULL,
  `Talla` CHAR(3) NULL,
  PRIMARY KEY (`idCotizacion_Producto`),
  INDEX `fk_Cotizacion_Productos_Cotizacion1_idx` (`Cotizacion_id` ASC) VISIBLE,
  INDEX `fk_Cotizacion_Productos_Color1_idx` (`Color_idColor` ASC) VISIBLE,
  CONSTRAINT `fk_Cotizacion_Productos_Cotizacion1`
    FOREIGN KEY (`Cotizacion_id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Cotizacion` (`idCotizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cotizacion_Productos_Color1`
    FOREIGN KEY (`Color_idColor`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`DetalleCompra` (
  `idDetalleCompra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Compras_Id` INT NOT NULL,
  `Color_id` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  INDEX `fk_DetalleCompra_Compras1_idx` (`Compras_Id` ASC) VISIBLE,
  INDEX `fk_DetalleCompra_Color1_idx` (`Color_id` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleCompra_Compras1`
    FOREIGN KEY (`Compras_Id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Compras` (`IdCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_Color1`
    FOREIGN KEY (`Color_id`)
    REFERENCES `PROYECTO ACCESORIO SIMPLE INVENTARIO`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
